package com.dev6.rejordbe.domain.exception;

/**
 * ExceptionCode
 */
public interface ExceptionCode {
    String ILLEGAL_UID = "ILLEGAL_UID";
    String ILLEGAL_USERID = "ILLEGAL_USERID";
    String ILLEGAL_NICKNAME = "ILLEGAL_NICKNAME";
    String ILLEGAL_PASSWORD = "ILLEGAL_PASSWORD";
    String ILLEGAL_ROLE = "ILLEGAL_ROLE";
    String ILLEGAL_DATE_TIME = "ILLEGAL_DATE_TIME";
    String ILLEGAL_CONTENTS = "ILLEGAL_CONTENTS";
    String ILLEGAL_PARAM = "ILLEGAL_PARAM";
    String ILLEGAL_ACCESS = "ILLEGAL_ACCESS";
    String DUPLICATED_NICKNAME = "DUPLICATED_NICKNAME";
    String DUPLICATED_USERID = "DUPLICATED_USERID";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String CHALLENGE_REVIEW_NOT_FOUND = "CHALLENGE_REVIEW_NOT_FOUND";
    String CHALLENGE_NOT_FOUND = "CHALLENGE_NOT_FOUND";
    String POST_NOT_FOUND = "POST_NOT_FOUND";

    // INTERNAL_SERVER_ERROR -------------------------------------
    String INTERNAL_ILLEGAL_PARAM = "INTERNAL_ILLEGAL_PARAM";
}
