spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

rejord:
  jwt:
    sort-key: ${SORT_KEY}
    access-token:
      period: 1800000 # ms
    refresh-token:
      period: 2592000000 # ms
